staging:
  host: http://0.0.0.0:5000
  handle: flowing-oasis-5896
  email: manuchap@gmail.com
  api_key: bb3be4f0209440288523f2b4ed6894fe2dd868d3
production:
  host: https://manuchap.herokuapp.com
  handle: pacific-fog-4242
  email: manuchap@gmail.com
  api_key: bb3be4f0209440288523f2b4ed6894fe2dd868d3
