address:
  label: Adress
  fields:
    street:
      hint: "Physical address of your store"
      type: string
    city:
      hint: "City you live in"
      type: string
contacts:
  label: contacts
  fields:
    email:
      hint: "Email address"
      type: string
    phone:
      hint: "Phone #"
      type: string
    fax:
      hint: "Fax #"
      type: string
links:
  label: links
  fields:
    link1_title:
      type: string
    link1_url:
      type: string
    link2_title:
      type: string
    link2_url:
      type: string
    link3_title:
      type: string
    link3_url:
      type: string
