# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

home:
  en: CLIENT AREA
  fr: ESPACE CLIENT
top:
  en: TOP
  fr: ACCUEIL
wedo:
  en: WEDO
  fr: DEMO
spec:
  en: HOW
  fr: TECH
pricing:
  en: PRICING
  fr: PRIX
